name: 🚀➕ Enhancement Request
description: Suggest an enhancement for this project or improve an existing feature.
# title: " "
labels: ['Type: Enhancement']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a new question or support request, please search open and closed issues to avoid duplication.

  - type: textarea
    id: what-happened
    attributes:
      label: What problem would you like to solve or improve?
      description: A clear and concise description of the problem or limitation.
      placeholder: Describe the problem or limitation you want to address.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe your proposed solution or enhancement.
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the solution or enhancement you are proposing.
    validations:
      required: true

  - type: textarea
    id: media-proof
    attributes:
      label: Describe any alternative solutions you've considered (optional).
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe any alternative solutions or features you've considered (optional).
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context or information (optional).
      description: Add any other context or additional information about the problem here.
      placeholder: Add any other context or additional information about the problem here (optional).
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
